/**
 * Mil_3100 - Stealth & Enemy AI Perception System (Phase 1)
 * Manages guard detection logic, vision cones, and hearing response to Mil's limp sound profile.
 */

class EnemyGuardAI {
    constructor(id, alertThreshold = 100) {
        this.guardId = id;
        this.state = "PATROL"; // PATROL, SUSPICIOUS, HUNTING, ENGAGED
        this.alertLevel = 0;   // 0 to 100
        this.alertThreshold = alertThreshold;
        this.visionConeAngle = 60; // 60 degrees field of view
        this.visionDistance = 15.0; // Max detection range in meters
        this.hearingSensitivity = 1.0;
    }

    /**
     * Evaluates sound generated by Mil's movement (taking into account the mechanical brace sound).
     */
    listenForNoise(noiseData, distanceToPlayer) {
        if (distanceToPlayer <= 0) return;

        // Sound dissipates with distance
        const effectiveNoise = (noiseData.leftStepNoise + noiseData.rightStepNoise) / (distanceToPlayer * 0.8);

        if (effectiveNoise > 10.0 * this.hearingSensitivity) {
            this.alertLevel += effectiveNoise * 1.5;
            this.updateState();
        }
    }

    /**
     * Calculates line of sight and visibility factor based on player status.
     */
    checkLineOfSight(distanceToPlayer, playerIsBraced, isLightArea) {
        if (distanceToPlayer > this.visionDistance) return false;

        let visibilityMultiplier = isLightArea ? 1.0 : 0.4;
        if (playerIsBraced) visibilityMultiplier *= 0.5; // Low profile reduces detection

        const detectedSightValue = (this.visionDistance - distanceToPlayer) * visibilityMultiplier * 10;
        
        if (detectedSightValue > 0) {
            this.alertLevel += detectedSightValue;
            this.updateState();
            return true;
        }
        return false;
    }

    /**
     * Updates AI behavior state according to cumulative alert level.
     */
    updateState() {
        if (this.alertLevel >= this.alertThreshold) {
            this.state = "ENGAGED";
        } else if (this.alertLevel >= 50) {
            this.state = "HUNTING";
        } else if (this.alertLevel >= 20) {
            this.state = "SUSPICIOUS";
        } else {
            this.state = "PATROL";
        }
    }
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { EnemyGuardAI };
}
